//! Ely embeds its own icons and fonts; the app adds its sample data (compiled
//! in, not served) and serves `glow.png`, the backdrop behind every screen.

use std::borrow::Cow;

use gpui::{AssetSource, SharedString};

pub const SAMPLES_JSON: &str = include_str!("../assets/samples.json");

/// The backdrop glow, generated by `scripts/glow.py`.
pub const GLOW_PNG: &[u8] = include_bytes!("../assets/glow.png");
/// Its light-mode twin (`scripts/glow.py --light`).
pub const GLOW_LIGHT_PNG: &[u8] = include_bytes!("../assets/glow-light.png");

/// Ely's assets. Kept as a wrapper so app assets can be layered in later.
pub struct AppAssets;

impl AssetSource for AppAssets {
    fn load(&self, path: &str) -> gpui::Result<Option<Cow<'static, [u8]>>> {
        match path {
            "glow.png" => return Ok(Some(Cow::Borrowed(GLOW_PNG))),
            "glow-light.png" => return Ok(Some(Cow::Borrowed(GLOW_LIGHT_PNG))),
            _ => {}
        }
        ely_gpui_component::Assets.load(path)
    }

    fn list(&self, path: &str) -> gpui::Result<Vec<SharedString>> {
        ely_gpui_component::Assets.list(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn serves_the_glow_png() {
        let bytes = AppAssets.load("glow.png").unwrap().expect("glow.png is embedded");
        assert_eq!(&bytes[..8], b"\x89PNG\r\n\x1a\n");
    }
}
